version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region eu-west-2)
  build:
    commands:
      - echo Build started on `date`
      - echo Building service1 Docker image...
      - docker build -t service1 ./services/service1
      - docker tag service1:latest 524455413981.dkr.ecr.eu-west-2.amazonaws.com/service1:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 524455413981.dkr.ecr.eu-west-2.amazonaws.com/service1:latest
